#!/bin/bash
printf "\n"
printf " * HoffmanOS Documentation:       https://github.com/christianhaitian/hoffmanos/wiki\n"
printf " * Debian Reference:             https://www.debian.org/doc/manuals/debian-reference/index.en.html\n"
printf "\n"
